
CREATE FUNCTION hello_function() RETURNS TEXT
  AS 'MODULE_PATHNAME'
  LANGUAGE C STRICT IMMUTABLE;

CREATE FUNCTION further_function() RETURNS TEXT
  AS 'MODULE_PATHNAME'
  LANGUAGE C STRICT IMMUTABLE;